// Per-element attribute reference, so get_element can teach an AI the MEANINGFUL keys
// of each BuilderX element (specials/config/events/bindings) — not just the empty
// factory skeleton (117/132 factories ship empty specials). Sources of truth:
//   - builderx_spa/src/common/data.js (real example nodes)
//   - builderx_spa/src/common/factory.js (per-type factories)
//   - builderx_spa panel/trait components
//   - real published pages mined from the backend DB
// Only real keys are listed here (no invented attributes).
import { readFileSync } from "node:fs";

// Comprehensive per-type key map, generated by mining real published pages across many
// sites + factory defaults (scripts produce src/builder/element-keys.generated.json,
// mirrored into dist by copy-assets). Gives the FULL real key surface of every element;
// the curated tables below add human meaning on top. Best-effort load (empty if absent).
type ObservedKeys = { seen?: number; specials: string[]; config: string[]; style: string[]; bindings: string[]; events: boolean };
let OBSERVED: Record<string, ObservedKeys> = {};
try {
  OBSERVED = JSON.parse(readFileSync(new URL("./element-keys.generated.json", import.meta.url), "utf8"));
} catch {
  OBSERVED = {};
}

// Editor-internal / junk keys to hide from the attribute report.
const NOISE_KEYS = new Set(["undefined", "locked", "loaded", "isChangeSection"]);

export interface ElementAttrs {
  /** Element-specific specials: content + behaviour. */
  specials?: Record<string, string>;
  /** Element-specific runtime.config keys BEYOND the generic grid ones. */
  config?: Record<string, string>;
  /** What events the element commonly carries (events[] = click/hover/... actions). */
  events?: string;
  /** Binding target strings (source::field) for dataset elements. */
  bindings?: string[];
  /** One-line authoring note. */
  notes?: string;
}

// Cross-cutting specials available on virtually every element.
export const SHARED_SPECIALS: Record<string, string> = {
  custom_class: "CSS class(es) on the element — target it with .your-class in site custom CSS.",
  custom_css: "Raw CSS scoped to this element.",
  element_async: "Mark the element async/lazy (advanced — usually leave unset).",
  event_name_custom: "Custom analytics event name fired on interaction.",
};

// Generic layout keys every node's runtime.config may carry (documented in the build
// guide); listed here so describeAttributes can flag them as 'generic, not element-specific'.
export const GENERIC_CONFIG = new Set([
  "grid", "columns", "rows", "columnStart", "columnEnd", "rowStart", "rowEnd",
  "constraintX", "constraintY", "heightUnit", "widthUnit", "loaded", "area", "lockCellGrid",
  "isHidden", "position", "isChangeSection", "useStickyLayoutOther", "columnGap", "rowGap",
  // absolute/relative position internals (set by the editor, not authored by hand):
  "absBottom", "absBottomCenterY", "absLeftCenterX", "absRight", "absRightCenterX", "absTopCenterY",
  "relBottom", "relBottomCenterY", "relLeftCenterX", "relRight", "relRightCenterX", "relTop",
  "relTopCenterY", "relLeft", "relWidth", "relHeight", "vhHeight", "vwHeight", "relMaxWidth",
  "leftUnit", "rightUnit", "topUnit", "bottomUnit", "topCenterYUnit", "rightCenterXUnit",
  "widthScreen", "cornerRadiusUnit", "borderEdges", "widthBg", "heightBg", "topBg", "leftBg",
  "rightBg", "bottomBg", "scaleX", "scaleY", "scaleL", "scaleT", "origin", "activeIndex",
]);

// Cross-element key dictionary: meanings for keys that recur across many element types
// (so even un-curated elements get useful descriptions). specials + config keys mixed.
export const SHARED_KEY_DICT: Record<string, string> = {
  // content / generic
  text: "Text / HTML content.",
  tag: "Semantic tag (h1..h6, p).",
  src: "Media URL (hosted).",
  image_alt: "Alt text (SEO / accessibility).",
  typographyTheme: "Apply a site typography preset.",
  text_animation_type: "Text entrance animation.",
  marker: "List marker style (none/dotList/numberList/imageList).",
  tabIndex: "Tab/focus order.",
  shapeType: "Shape kind (rectangle/etc.).",
  // layout / display
  displayStyle: "Visual layout variant of the element.",
  columns: "Number of columns / items per row.",
  responsive: "Responsive sizing mode (autofit/fixed).",
  gap_column: "Horizontal gap between items (px).",
  gap_row: "Vertical gap between items (px).",
  image_ratio: "Image aspect ratio (16/9, 4/3, 1/1, …).",
  img_object_fit: "Image fit: cover/contain/fill/stretch.",
  image_width: "Image width within the card.",
  image_placement: "Image position relative to text (column/row).",
  slideItems: "Visible slides/items in a slider.",
  slideWidth: "Slide/card width (px).",
  item_show: "How many items to display.",
  autoplay: "Auto-advance (boolean).",
  loop: "Loop playback/slides (boolean).",
  showControl: "Show playback/nav controls (boolean).",
  minimum_card_width: "Minimum card width (px, autofit).",
  // links / nav
  link: "Destination URL (custom link).",
  linkType: "Link kind: page|category|blog_category|brand|product_tag|custom.",
  linkPage: "Target page id (linkType=page).",
  linkPageTarget: "Open target for the page link (_self/_blank).",
  linkCategory: "Target product category id.",
  linkBlogCategory: "Target blog category id.",
  linkTarget: "Open target (_self/_blank).",
  categoryId: "Category id this item points to.",
  isCustom: "Use a custom link instead of an internal target (boolean).",
  isSync: "Auto-sync with site pages/categories (boolean).",
  name: "Display label.",
  // commerce
  category_id: "Product category id to source items from.",
  products_per_load: "Products fetched per page/scroll.",
  promotion_id: "Linked promotion id.",
  original_price_position: "Where the compare-at price shows (left/right).",
  show_categories: "Show category labels (boolean).",
  // form (also in FIELD below)
  options: "Choices [{id,name}] for a select/radio/checkbox.",
  field_type: "Underlying field type.",
};

// Common form-field specials reused by every input-like element.
const FIELD = {
  field_name: "Submission key this field maps to (e.g. full_name, email, phone_number, note, address, password).",
  label: "Visible label text.",
  placeholder: "Placeholder text.",
  show_label: "Show the label (boolean).",
  required: "Field is required (boolean).",
  validate: "Enable validation (boolean).",
};

export const ELEMENT_ATTRS: Record<string, ElementAttrs> = {
  // ── content ──
  text: {
    specials: { text: "Rich text / HTML content.", tag: "Semantic tag: h1|h2|h3|h4|h5|h6|p.", typographyTheme: "Apply a site typography preset.", marker: "List marker: none|dotList|numberList|imageList." },
    config: { strokeColor: "Text stroke colour." },
    events: "click, hover (in events[]) — links/actions on text are common.",
    notes: "Set specials.text (HTML) + specials.tag. Style via runtime.style (color, fontSize, fontWeight, textAlign, lineHeight, letterSpacing).",
  },
  "text-dataset": {
    config: {}, events: "none",
    bindings: ["product::product_name", "product::product_price", "cart_item::cart_item_name", "cart_item::cart_item_price", "order_item::product_name", "customer_address::full_name"],
    notes: "Text bound to live data — set bindings[].target to a source::field; no static specials.text.",
  },
  image: {
    specials: { src: "Image URL (hosted).", image_alt: "Alt text (SEO/accessibility)." },
    config: { src: "Image URL (mirror of specials.src).", ratio: "Aspect ratio.", minWidth: "Min width (px).", minHeight: "Min height (px).", sizeThumbnail: "Thumbnail size." },
    events: "click, hover (link/lightbox) — very common.",
    notes: "Put the hosted URL in runtime.config.src (and specials.src). Use search_images/upload_images to get URLs.",
  },
  "image-dataset": {
    events: "none",
    bindings: ["product::product_image", "cart_item::cart_item_image", "order_item::product_image", "customer_address::pdc"],
    notes: "Image bound to live data — set bindings[].target; no static src.",
  },
  video: {
    specials: { src: "Video URL.", thumbnail: "Poster image URL.", time: "Duration label (e.g. '10.0s').", type: "Source type (e.g. store)." },
    events: "none",
  },
  "video-dataset": { events: "none", bindings: ["lesson::lesson_video"], notes: "Video bound to a dataset field." },
  rectangle: {
    specials: { shapeType: "Shape kind.", custom_css: "Raw CSS for the shape." },
    config: { mask: "Mask id/shape.", maskId: "Mask reference." },
    events: "click, hover — often used as a clickable card/background.",
    notes: "Coloured box / divider / background. Style via runtime.style (background, border*, boxShadow).",
  },
  line: { events: "none", notes: "Separator line — style via runtime.style background/border." },
  gallery: { specials: { media: "Array of media (image) objects." }, config: { showThumbnail: "Show thumbnails.", showNavigation: "Show nav arrows.", thumbnailPosition: "none|top|bottom|left|right." }, events: "none" },
  carousel: { config: { slideWidth: "Slide width (px).", slideItems: "Visible slides count." }, events: "none", notes: "Holds slide children." },
  swiper: { config: {}, events: "none", notes: "Swiper carousel — holds slide children." },
  slide: { events: "none", notes: "A single slide inside a carousel/swiper." },
  embed: { specials: { iframe: "Raw HTML / iframe markup." }, events: "none" },
  googlemap: { specials: { iframe: "Google Maps embed iframe string." }, events: "none" },
  countdown: { specials: { time: "Target date/time.", type: "Countdown mode." }, events: "none", notes: "Timer; check the live skeleton for exact specials." },
  breadcrumb: { specials: { options: "Per-context paths (search/product/category/blog/post/default).", icon: "Separator string e.g. '>'." }, events: "none" },
  "list-ordered": { specials: { tableItems: "Column definitions [{name,key,i18nKey}]." }, events: "none" },

  // ── layout ──
  section: {
    specials: { global: "Mark as a global/shared section (reused across pages).", custom_class: "CSS class.", layout: "Nested layout payload (advanced)." },
    events: "none",
    notes: "Top-level band; centred 3-column grid. Children go in the centre column (new_section handles this).",
  },
  container: { specials: { tabIndex: "Tab order.", custom_class: "CSS class.", custom_css: "Raw CSS." }, config: { maxWidth: "Max width.", maxWidthUnit: "Max-width unit.", fixedPosition: "Sticky/fixed positioning.", animation: "Entrance animation." }, events: "click, hover — clickable groups are common.", notes: "Generic grid box; nest children with their own grid." },
  row: { events: "none", notes: "Simple horizontal wrapper." },
  tabs: { specials: { activeTab: "Default active tab index." }, events: "none", notes: "Tabbed container." },
  collapse: { events: "none", notes: "Accordion container (collapse-item children)." },
  "collapse-item": { events: "none", notes: "One accordion panel." },
  "custom-layout": { events: "none", notes: "Free-form layout container." },
  "layout-dataset": { events: "none", bindings: ["product::*"], notes: "Repeating layout bound to a dataset." },

  // ── button ──
  button: { specials: { text: "Button label." }, events: "click — set the action in events[] (open page/link/scroll/popup/add-to-cart...).", notes: "Label in specials.text; behaviour in events[]." },
  "submit-button": { specials: { text: "Button label (e.g. 'Đăng nhập')." }, events: "submit — submits its parent form.", notes: "Place inside a form." },
  "paypal-button": { events: "none", notes: "PayPal payment button (provider-handled)." },
  "button-login-google": { specials: { text: "Label e.g. 'Đăng nhập với Google'." }, events: "click (OAuth)." },
  "button-login-facebook": { specials: { text: "Label e.g. 'Đăng nhập với Facebook'." }, events: "click (OAuth)." },
  "current-location": { specials: { text: "Label.", field_name: "current location.", field_type: "current-location." }, events: "click (geolocation)." },

  // ── form ──
  form: {
    specials: {
      type: "Form behaviour — one of: form_login | form_signup | form_order | form_discount | subscribe | order_tracking | form_booking | form_search_agency | question_form.",
      submit_success: "Action after a successful submit (e.g. show a message / redirect).",
      message: "Success message text.",
      show_message: "Show a success message after submit (boolean).",
      show_message_time: "How long the success message stays (seconds).",
    },
    config: { backgroundInput: "Input background.", labelColor: "Label colour.", placeholderColor: "Placeholder colour.", textPadding: "Input padding (px).", labelMarginBottom: "Gap below label (px).", borderColor: "Input border colour (e.g. #dbe0e6).", borderRadius: "Input corner radius (e.g. 8px)." },
    events: "success — fire follow-up actions after a successful submit (a form_order commonly does open_page→Thank-you page). eventName defaults to 'success' on a form.",
    notes: "Wrap input fields as children; put a submit-button inside. specials.type selects what the form does on submit. Real order forms split fields across an inner form via specials.multiForms:[innerFormId] (inner form sets specials.formParent). A form_order uses dedicated field types: input(full_name), phone-number, email, detect-address, address (×3 province/district/ward), text-area(note).",
  },
  input: { specials: { ...FIELD, type: "Input type (default text)." }, config: { textPadding: "Padding.", backgroundInput: "Background." }, events: "none" },
  email: { specials: { ...FIELD, validate_email: "Email regex." }, events: "none", notes: "field_name usually 'email'." },
  "phone-number": { specials: { ...FIELD }, events: "none", notes: "field_name usually 'phone_number'." },
  "retype-phone-number": { specials: { ...FIELD }, events: "none" },
  password: { specials: { ...FIELD, field_type: "password.", validate_password: "Password regex." }, events: "none", notes: "field_name 'password'." },
  "retype-password": { specials: { ...FIELD, validate_password: "Password regex." }, events: "none" },
  "current-password": { specials: { ...FIELD, validate_password: "Password regex." }, events: "none" },
  "text-area": { specials: { ...FIELD }, events: "none", notes: "Multi-line; field_name often 'note'." },
  select: { specials: { ...FIELD, options: "Choices [{id,name}] (or {type,name,image,active}).", defaultValue: "Selected option id." }, config: { arrowColor: "Dropdown arrow colour.", optionBorderColor: "Option border." }, events: "none" },
  "group-select": { specials: { ...FIELD, options: "Choices [{id,name}]." }, events: "none" },
  checkbox: { specials: { field_name: FIELD.field_name, label: FIELD.label, show_label: FIELD.show_label, required: FIELD.required }, events: "none" },
  "checkbox-group": { specials: { ...FIELD, options: "Choices [{id,name}]." }, config: { gap: "Item spacing.", column: "Columns." }, events: "none" },
  "checkbox-item": { specials: { label: "Option text." }, events: "none" },
  radio: { specials: { field_name: FIELD.field_name, label: FIELD.label, show_label: FIELD.show_label, required: FIELD.required }, events: "none" },
  "radio-group": { specials: { ...FIELD, options: "Choices [{id,name,events?,connects?}]." }, config: { gap: "Item spacing.", column: "Columns." }, events: "none" },
  address: { specials: { field_name: "province_id/district_id/commune_id.", label: FIELD.label, placeholder: FIELD.placeholder, show_label: FIELD.show_label, country: "Country code (e.g. 84).", required_province: "Require province.", required_districts: "Require district.", required_commune: "Require commune." }, events: "none" },
  "detect-address": { specials: { ...FIELD, field_type: "detect_address." }, events: "none" },
  "postal-code": { specials: { ...FIELD }, events: "none" },
  country: { specials: { ...FIELD }, events: "none" },
  "input-file": { specials: { ...FIELD, isTransferImage: "Transfer as image (boolean)." }, events: "none" },
  "input-number": { specials: { ...FIELD }, events: "none" },
  "input-date": { specials: { ...FIELD, type: "date | time." }, events: "none" },
  "input-search": { specials: { field_name: "search.", label: FIELD.label, placeholder: FIELD.placeholder }, events: "none" },
  "otp-input": { specials: { ...FIELD, isOpenModalOtp: "Open OTP modal (boolean)." }, events: "none" },
  "rating-input": { specials: { field_name: FIELD.field_name, label: FIELD.label, show_label: FIELD.show_label }, events: "none" },
  identity: { specials: { ...FIELD }, events: "none", notes: "Email-or-phone login field; field_name 'identity'." },
  switch: { events: "none", notes: "Toggle; style width/height." },

  // ── commerce ──
  "grid-product": {
    specials: { displayStyle: "default | only_image | border.", original_price_position: "left | right.", products_per_load: "Products fetched per page/scroll (real default 36).", show_original_price: "Show the compare-at price (boolean).", show_discount_on_price: "Show a discount badge on the price (boolean).", show_quick_view: "Show a quick-view button on hover (boolean)." },
    config: { columns: "Products per row.", responsive: "autofit | fixed | custom.", item_show: "How many products to show.", image_ratio: "16/9|3/2|4/3|1/1|4/5|9/16|2/3|3/4 (designer templates use 4/5).", img_object_fit: "cover|contain|fill|stretch.", gap_column: "Column gap (real default 30).", gap_row: "Row gap (real default 15).", product_info_padding_y: "Vertical padding of the name/price block (px).", price_padding_y: "Vertical padding around the price (px).", product_info_alignment: "left|center|right.", productNameFont: "Product-name font family.", productNameFontSize: "Product-name font size (px).", productPriceFont: "Price font family.", productPriceFontSize: "Price font size (px).", productPriceFontWeight: "Price font weight (e.g. bold).", productOriginalPriceFontSize: "Compare-at price font size (px).", sizeThumbnail: "{ width, height } of the card image." },
    events: "none",
    bindings: ["product::product_image", "product::product_name", "product::product_price"],
    notes: "Lists store products (self-renders image+name+price card). Requires a 'store' page / use_store. Configure columns + image_ratio (4/5 reads as a fashion card); the price/name fonts + show_* flags style the card.",
  },
  "slider-product": { specials: { displayStyle: "default|only_image|border.", original_price_position: "left|right." }, config: { slideItems: "Visible products.", slideWidth: "Card width.", image_ratio: "Aspect ratio." }, events: "none", bindings: ["product::product_image", "product::product_name", "product::product_price"] },
  "product-gallery": { events: "none", notes: "Product detail image gallery (product page)." },
  "product-image-carousel": { events: "none", notes: "Product image carousel (product page)." },
  "cart-items": { events: "none", bindings: ["cart_item::cart_item_image", "cart_item::cart_item_name", "cart_item::cart_item_price", "cart_item::cart_item_total_price", "cart_item::cart_item_prod_attr"], notes: "Cart line items (cart page). A repeater whose config.columns defines the per-row column template — real templates use [70px image, 1fr name, ~240px price, ~116px qty, ~240px total, 34px remove]." },
  "cart-icon": { specials: { svg: "Icon SVG (defaults to a bag icon; fill='currentColor' so it inherits style.color).", itemCount: "Badge count (0 placeholder)." }, config: { itemCountFontFamily: "Badge font family.", itemCountFontSize: "Badge font size (e.g. 11px).", itemCountColor: "Badge text colour.", itemCountBorderRadius: "Badge corner radius (50% = circle)." }, events: "click — opens cart. Real templates wrap it in a container with open_popup(mouseenter)/close_popup(mouseleave) for a mini-cart, plus a container with open_page→cart page." },
  "quantity-input": { events: "none", notes: "Quantity stepper (product/cart)." },
  attr: { events: "none", notes: "Product attribute selector (variations)." },
  payment: { events: "none", notes: "Payment methods block (checkout)." },
  "delivery-method": { specials: { options: "[{type: delivery|store_pickup, name, active}]." }, events: "none" },
  "order-items": { events: "none", bindings: ["order_item::product_image", "order_item::product_name", "order_item::product_quantity", "order_item::product_attrs", "order_item::items_sum_up_price"], notes: "Order summary lines (checkout/thank-you). Repeater whose config.columns is the per-row template — real templates use [75px image, 1fr name, 95px price]." },
  "order-history": { events: "none", notes: "Member order history (member page)." },
  coupon: { events: "none", notes: "Coupon / discount code input." },
  "product-overlay": { specials: { type: "discount | custom." }, events: "none", notes: "Badge overlaid on a product card." },
  "product-review": {
    specials: {
      title: "Heading text.", show_heading: "Show the heading (boolean).", reviews_per_page: "Reviews per page.",
      show_avatar: "Show reviewer avatar (boolean).", avatar_size: "Avatar size (px).", reply_avatar_size: "Reply avatar size (px).",
      avatar_border_radius: "Avatar corner radius.", avatar_border_color: "Avatar border colour.", avatar_border_size: "Avatar border width.",
      show_rating_breakdown: "Show the star breakdown (boolean).", show_sorting: "Show sort control (boolean).", show_filter: "Show filter (boolean).",
      show_publish_date: "Show the review date (boolean).", require_email: "Require email to review (boolean).", require_phone_number: "Require phone (boolean).",
      type_view_more: "How more reviews load (paginate/expand).",
    },
    events: "none", notes: "Product reviews block (product page).",
  },
  "number-step": {
    specials: {
      minValue: "Minimum value.", maxValue: "Maximum value.", numberUnit: "Unit label.", count: "Step amount.",
      filter: "Filter mode.", use_button_filter: "Use buttons to filter (boolean).", shortened: "Abbreviate large numbers (boolean).",
    },
    events: "none", notes: "Numeric stepper / counter.",
  },
  "masonry-review": { specials: { view_product_mode: "How linked products display in the review wall." }, events: "none", notes: "Masonry wall of reviews." },
  "flash-sale": { specials: { promotion_advance_id: "Promotion id (or 'none')." }, events: "none" },
  promotions: { events: "none", bindings: ["promotion_item::image", "promotion_item::name", "promotion_item::code", "promotion_item::description", "promotion_item::end_date"] },
  "promotions-short": { events: "none", bindings: ["promotion_item::name", "promotion_item::code"] },
  "grid-category": { config: { columns: "Categories per row." }, events: "none", notes: "Lists product categories. Create categories first (create_product_category)." },
  "slider-category": { config: { columns: "Visible categories." }, events: "none" },
  "customer-address": { events: "none", bindings: ["customer_address::full_name", "customer_address::address", "customer_address::phone_number", "customer_address::pdc", "customer_address::is_default"], notes: "Member saved addresses." },
  wishlist: { specials: { svg: "Icon SVG.", itemCount: "Badge count." }, events: "click." },
  "favorite-icon": { events: "click — toggle favourite." },
  "bonus-items": { specials: { typeBonus: "combo_product | other." }, events: "none" },

  // ── navigation ──
  menu: { specials: { type: "horizontal | vertical | hamburger | anchor.", sync: "Auto-sync items with site pages (boolean).", fullField: "Stretch items to fill the menu width (boolean)." }, config: { showArrow: "Show the dropdown caret on items with a submenu (boolean).", textColor: "Item text colour (often a theme var like var(--color_20)).", colorHover: "Item hover colour.", "--padX": "Horizontal padding inside each item (CSS var, e.g. 15px)." }, events: "none", notes: "Holds menu-item children. Real templates colour items via theme vars (var(--color_20))." },
  "menu-item": { specials: { name: "Link label.", isCustom: "Custom link (boolean).", linkType: "page | category | blog_category | brand | product_tag | custom.", linkPage: "Target page id (linkType=page).", pageId: "Target page id (mirror of linkPage, set both).", linkCategory: "Linked category id.", categoryId: "Category id.", syncSubmenu: "Auto-build submenu (boolean)." }, events: "navigation lives in SPECIALS here, NOT events — set linkType + the matching id.", notes: "For a page link set linkType='page' + linkPage + pageId + name. (Generic text/container/button elements navigate via events:[{action:'open_page',open_page_id}] instead.)" },
  "menu-anchor-item": { specials: { name: "Label.", isCustom: "Custom.", linkType: "Link kind.", categoryId: "Category id." }, events: "click — scrolls to an anchor." },
  submenu: { events: "none", notes: "Dropdown under a menu-item." },
  "menu-droppable": { events: "none" },
  "member-bar": { events: "none", notes: "Logged-in member bar (account links)." },
  "member-dropdown": { events: "none" },
  dropdown: { events: "click/hover — toggles dropdown-content." },
  "dropdown-content": { events: "none" },
  "language-menu": { events: "none", notes: "Language switcher." },

  // ── blog ──
  "post-list": { events: "none", notes: "Lists blog articles. Create blog category + articles first." },
  "slider-post": { config: { slideItems: "Visible posts.", slideWidth: "Card width." }, events: "none" },
  "grid-blog": { specials: { showBlogs: "Categories to show [{...}]." }, config: { columns: "Posts per row." }, events: "none" },
  "slider-blog": { specials: { showBlogs: "Categories to show." }, config: { columns: "Visible posts." }, events: "none" },
  "post-overlay": { specials: { type: "regular | custom." }, events: "none", notes: "Post card overlay (post page)." },
  "blog-overlay": { specials: { type: "regular | custom." }, events: "none" },
};

const describe = (type: string, key: string, where: "specials" | "config"): string | undefined => {
  const curated = ELEMENT_ATTRS[type] || {};
  return (curated[where] && curated[where]![key]) || SHARED_KEY_DICT[key] || (where === "specials" ? SHARED_SPECIALS[key] : undefined);
};

/**
 * Build a COMPLETE attribute report for an element type, merging three sources:
 *  - curated tables (ELEMENT_ATTRS) + dictionaries (human meaning),
 *  - the full real key surface mined from published pages + factory defaults (OBSERVED),
 *  - the live skeleton (factory defaults).
 * Every real key is surfaced; ones we have meaning for are described, the rest are
 * listed by name so the AI knows they exist. No invented keys.
 */
export function describeAttributes(type: string, skeleton: any): any {
  const curated = ELEMENT_ATTRS[type] || {};
  const obs = OBSERVED[type] || { specials: [], config: [], style: [], bindings: [], events: false };
  const skSpecials = (skeleton && skeleton.specials) || {};
  const skConfig = (skeleton && ((skeleton.runtime && skeleton.runtime.config) || skeleton.config)) || {};

  // ── specials: every real key, described where known ──
  const specialKeys = new Set<string>([
    ...Object.keys(curated.specials || {}),
    ...obs.specials,
    ...Object.keys(skSpecials),
  ]);
  const specials: Record<string, string> = {};
  const moreSpecials: string[] = [];
  for (const k of [...specialKeys].sort()) {
    if (NOISE_KEYS.has(k) || k in SHARED_SPECIALS) continue; // shared ones listed separately
    const d = describe(type, k, "specials");
    if (d) specials[k] = d;
    else moreSpecials.push(k);
  }

  // ── config: element-specific only (drop generic grid/position internals) ──
  const configKeys = new Set<string>([
    ...Object.keys(curated.config || {}),
    ...obs.config,
    ...Object.keys(skConfig),
  ]);
  const config: Record<string, string> = {};
  const moreConfig: string[] = [];
  for (const k of [...configKeys].sort()) {
    if (NOISE_KEYS.has(k) || GENERIC_CONFIG.has(k)) continue;
    const d = describe(type, k, "config");
    if (d) config[k] = d;
    else moreConfig.push(k);
  }

  const style = (obs.style || []).filter((k) => !NOISE_KEYS.has(k)).sort();

  return {
    specials: Object.keys(specials).length ? specials : undefined,
    more_specials: moreSpecials.length ? moreSpecials : undefined, // real but un-annotated
    common_specials: Object.keys(SHARED_SPECIALS), // available on almost every element
    config: Object.keys(config).length ? config : undefined,
    more_config: moreConfig.length ? moreConfig : undefined, // real but un-annotated (mostly visual)
    style: style.length ? style : undefined,
    events: curated.events || (obs.events ? "supports events[] (click/hover/submit actions)" : "none observed"),
    bindings: (curated.bindings && curated.bindings.length ? curated.bindings : obs.bindings) || undefined,
    notes: curated.notes,
    common_specials_note: "custom_class/custom_css/element_async/event_name_custom work on almost every element.",
    layout_hint: "runtime.style holds CSS (width/height/color/fontSize/background/border…); runtime.config holds grid placement (see get_build_guide). On save these expand into bp1..bp4.",
    events_hint: "Attach interactions via opts.events (ids auto-minted). Call list_events for the trigger/action catalog + required fields.",
    bindings_hint: "Attach dynamic data via opts.bindings (ids auto-minted). Call list_bindings for the dataset/field catalog. Inside a repeater (grid-product/cart-items/post-list…) children bind to the per-item dataset.",
    coverage: obs.seen ? `${obs.seen} real instances mined` : "factory default only",
  };
}
