// Per-element attribute reference, so get_element can teach an AI the MEANINGFUL keys
// of each BuilderX element (specials/config/events/bindings) — not just the empty
// factory skeleton (117/132 factories ship empty specials). Sources of truth:
//   - builderx_spa/src/common/data.js (real example nodes)
//   - builderx_spa/src/common/factory.js (per-type factories)
//   - builderx_spa panel/trait components
//   - real published pages mined from the backend DB
// Only real keys are listed here (no invented attributes).
import { readFileSync } from "node:fs";

// Comprehensive per-type key map, generated by mining real published pages across many
// sites + factory defaults (scripts produce src/builder/element-keys.generated.json,
// mirrored into dist by copy-assets). Gives the FULL real key surface of every element;
// the curated tables below add human meaning on top. Best-effort load (empty if absent).
type ObservedKeys = { seen?: number; specials: string[]; config: string[]; style: string[]; bindings: string[]; events: boolean };
let OBSERVED: Record<string, ObservedKeys> = {};
try {
  OBSERVED = JSON.parse(readFileSync(new URL("./element-keys.generated.json", import.meta.url), "utf8"));
} catch {
  OBSERVED = {};
}

// Editor-internal / junk keys to hide from the attribute report.
const NOISE_KEYS = new Set(["undefined", "locked", "loaded", "isChangeSection"]);

export interface ElementAttrs {
  /** Element-specific specials: content + behaviour. */
  specials?: Record<string, string>;
  /** Element-specific runtime.config keys BEYOND the generic grid ones. */
  config?: Record<string, string>;
  /** What events the element commonly carries (events[] = click/hover/... actions). */
  events?: string;
  /** Binding target strings (source::field) for dataset elements. */
  bindings?: string[];
  /** One-line authoring note. */
  notes?: string;
}

// Cross-cutting specials available on virtually every element.
export const SHARED_SPECIALS: Record<string, string> = {
  custom_class: "CSS class(es) on the element — target it with .your-class in site custom CSS.",
  custom_css: "Raw CSS scoped to this element.",
  element_async: "Mark the element async/lazy (advanced — usually leave unset).",
  event_name_custom: "Custom analytics event name fired on interaction.",
  tabIndex: "Bind this element to a tab item (TAB-ITEM-…) so a tabs element shows/hides it.",
  text_animation_type: "Entrance animation for the element's text (none|…).",
};

// Generic layout keys every node's runtime.config may carry (documented in the build
// guide); listed here so describeAttributes can flag them as 'generic, not element-specific'.
export const GENERIC_CONFIG = new Set([
  "grid", "columns", "rows", "columnStart", "columnEnd", "rowStart", "rowEnd",
  "constraintX", "constraintY", "heightUnit", "widthUnit", "loaded", "area", "lockCellGrid",
  "isHidden", "position", "isChangeSection", "useStickyLayoutOther", "columnGap", "rowGap",
  // absolute/relative position internals (set by the editor, not authored by hand):
  "absBottom", "absBottomCenterY", "absLeftCenterX", "absRight", "absRightCenterX", "absTopCenterY",
  "relBottom", "relBottomCenterY", "relLeftCenterX", "relRight", "relRightCenterX", "relTop",
  "relTopCenterY", "relLeft", "relWidth", "relHeight", "vhHeight", "vwHeight", "relMaxWidth",
  "leftUnit", "rightUnit", "topUnit", "bottomUnit", "topCenterYUnit", "rightCenterXUnit",
  "widthScreen", "cornerRadiusUnit", "borderEdges", "widthBg", "heightBg", "topBg", "leftBg",
  "rightBg", "bottomBg", "scaleX", "scaleY", "scaleL", "scaleT", "origin", "activeIndex",
]);

// Cross-element key dictionary: meanings for keys that recur across many element types
// (so even un-curated elements get useful descriptions). specials + config keys mixed.
export const SHARED_KEY_DICT: Record<string, string> = {
  // content / generic
  text: "Text / HTML content.",
  tag: "Semantic tag (h1..h6, p).",
  src: "Media URL (hosted).",
  image_alt: "Alt text (SEO / accessibility).",
  typographyTheme: "Apply a site typography preset.",
  text_animation_type: "Text entrance animation.",
  marker: "List marker style (none/dotList/numberList/imageList).",
  tabIndex: "Tab/focus order.",
  shapeType: "Shape kind (rectangle/etc.).",
  // layout / display
  displayStyle: "Visual layout variant of the element.",
  columns: "Number of columns / items per row.",
  responsive: "Responsive sizing mode (autofit/fixed).",
  gap_column: "Horizontal gap between items (px).",
  gap_row: "Vertical gap between items (px).",
  image_ratio: "Image aspect ratio (16/9, 4/3, 1/1, …).",
  img_object_fit: "Image fit: cover/contain/fill/stretch.",
  image_width: "Image width within the card.",
  image_placement: "Image position relative to text (column/row).",
  slideItems: "Visible slides/items in a slider.",
  slideWidth: "Slide/card width (px).",
  item_show: "How many items to display.",
  autoplay: "Auto-advance (boolean).",
  loop: "Loop playback/slides (boolean).",
  showControl: "Show playback/nav controls (boolean).",
  minimum_card_width: "Minimum card width (px, autofit).",
  // links / nav
  link: "Destination URL (custom link).",
  linkType: "Link kind: page|category|blog_category|brand|product_tag|custom.",
  linkPage: "Target page id (linkType=page).",
  linkPageTarget: "Open target for the page link (_self/_blank).",
  linkCategory: "Target product category id.",
  linkBlogCategory: "Target blog category id.",
  linkTarget: "Open target (_self/_blank).",
  categoryId: "Category id this item points to.",
  isCustom: "Use a custom link instead of an internal target (boolean).",
  isSync: "Auto-sync with site pages/categories (boolean).",
  name: "Display label.",
  // commerce
  category_id: "Product category id to source items from.",
  products_per_load: "Products fetched per page/scroll.",
  promotion_id: "Linked promotion id.",
  original_price_position: "Where the compare-at price shows (left/right).",
  show_categories: "Show category labels (boolean).",
  // form (also in FIELD below)
  options: "Choices [{id,name}] for a select/radio/checkbox.",
  field_type: "Underlying field type.",
};

// Common form-field specials reused by every input-like element.
const FIELD = {
  field_name: "Submission key this field maps to (e.g. full_name, email, phone_number, note, address, password).",
  label: "Visible label text.",
  placeholder: "Placeholder text.",
  show_label: "Show the label (boolean).",
  required: "Field is required (boolean).",
  validate: "Enable validation (boolean).",
};

// Common runtime.config keys shared by EVERY input-like field (mined from 34 templates).
// Spread into each field's `config` so they're documented everywhere.
const FIELD_CONFIG = {
  backgroundInput: "Input background colour.",
  placeholderColor: "Placeholder text colour.",
  labelColor: "Label colour.",
  labelMarginBottom: "Gap below the label (px).",
  textPadding: "Inner padding of the input (px).",
  optionBorderColor: "Input border colour.",
  optionBorderWidth: "Input border width (e.g. '1px').",
  optionBorderStyle: "Input border style (solid|dashed|none).",
  optionBorderRadius: "Input corner radius.",
};

// Filter-widget specials shared by category-page filters that drive a product grid
// (checkbox-group, color-group, radio-group, two-point-range, tags, dropdown). These wire a
// sidebar control to a grid-product so picking an option re-queries the products.
const FILTER_SPECIALS = {
  filter_elements: "Ids of the grid-product(s) this filter controls, e.g. ['GRID-PRODUCT-xxx'].",
  sync_tab: "What to filter by: attribute | brand | category | price | tag.",
  count: "How many options to show.",
  options: "Filter options [{id,name,...}] (auto-built when syncing).",
  is_auto_child_categories: "Auto-include child categories (boolean).",
  use_button_filter: "Apply only when an Apply button is clicked (boolean).",
};

export const ELEMENT_ATTRS: Record<string, ElementAttrs> = {
  // ── content ──
  text: {
    specials: { text: "Rich text / HTML content.", tag: "Semantic tag: h1|h2|h3|h4|h5|h6|p.", typographyTheme: "Apply a site typography preset.", marker: "List marker: none|dotList|numberList|imageList." },
    config: { strokeColor: "Text stroke colour." },
    events: "click, hover (in events[]) — links/actions on text are common.",
    notes: "Set specials.text (HTML) + specials.tag. Style via runtime.style (color, fontSize, fontWeight, textAlign, lineHeight, letterSpacing).",
  },
  "text-dataset": {
    specials: { tag: "Semantic tag (h1..h6/p) — set 'h1' for the product/post title." },
    config: { hover_color: "Text colour on hover." }, events: "none",
    bindings: ["product::product_name", "product::product_price", "cart_item::cart_item_name", "cart_item::cart_item_price", "order_item::product_name", "customer_address::full_name"],
    notes: "Text bound to live data — set bindings[].target to a source::field; no static specials.text.",
  },
  image: {
    specials: { src: "Image URL (hosted).", image_alt: "Alt text (SEO/accessibility)." },
    config: { src: "Image URL (mirror of specials.src).", ratio: "Aspect ratio.", minWidth: "Min width (px).", minHeight: "Min height (px).", sizeThumbnail: "Thumbnail size." },
    events: "click, hover (link/lightbox) — very common.",
    notes: "Put the hosted URL in runtime.config.src (and specials.src). Use search_images/upload_images to get URLs.",
  },
  "image-dataset": {
    events: "none",
    bindings: ["product::product_image", "cart_item::cart_item_image", "order_item::product_image", "customer_address::pdc"],
    notes: "Image bound to live data — set bindings[].target; no static src.",
  },
  video: {
    specials: { src: "Video URL.", thumbnail: "Poster image URL.", time: "Duration label (e.g. '10.0s').", type: "Source type (store|youtube).", id: "YouTube/provider video id.", autoplay: "Auto-play (boolean).", loop: "Loop (boolean).", showControl: "Show player controls (boolean)." },
    config: { ratio: "Aspect ratio (e.g. 0.5625 = 16/9).", src: "Video URL (mirror)." },
    events: "none",
  },
  "video-dataset": { specials: { autoRotateInMobile: "Rotate to landscape on mobile (boolean).", show_list_video_lesson: "Show the lesson playlist (boolean).", show_next_video_lesson: "Show the next-lesson button (boolean)." }, events: "none", bindings: ["lesson::lesson_video"], notes: "Video bound to a dataset field (course lesson video)." },
  rectangle: {
    specials: { shapeType: "Shape kind.", custom_css: "Raw CSS for the shape." },
    config: { mask: "Mask SVG/shape (clips the box into an icon).", maskId: "Mask reference.", custom_mask: "Custom mask SVG markup.", fixedPosition: "Pin/float the shape (bottom_right|…) — e.g. a floating badge.", animation: "Entrance animation." },
    events: "click, hover — often used as a clickable card/background.",
    notes: "Coloured box / divider / background. Style via runtime.style (background, border*, boxShadow).",
  },
  line: { specials: { type: "horizontal | vertical." }, events: "none", notes: "Separator line — style via runtime.style background/border." },
  gallery: { specials: { media: "Array of media (image) objects.", showNavigation: "Show nav arrows (boolean).", arrowColor: "Arrow colour.", autoplay_time: "Autoplay interval (s)." }, config: { showThumbnail: "Show thumbnails.", showNavigation: "Show nav arrows.", thumbnailPosition: "none|top|bottom|left|right.", image_ratio: "Image ratio (auto|…).", img_object_fit: "cover|contain.", showPaginate: "Pagination style (bar|none)." }, events: "none" },
  carousel: { specials: { type: "slide_only | …", autoplay: "on|off.", autoplay_time: "Seconds per slide.", arrowColor: "Arrow colour.", slides: "Slide list [{id,name}]." }, config: { slideWidth: "Slide width (px).", slideItems: "Visible slides count.", slideWidthUnit: "px|%.", showPaginate: "Pagination style (bar-dot|…).", paginateMode: "auto|manual.", arrowWidth: "Arrow width.", navColor: "Nav colour." }, events: "none", notes: "Holds slide children." },
  swiper: { specials: { autoplay: "on|off.", autoplayDelay: "ms between slides.", paginate: "Show pagination (boolean).", paginateBar: "bullet|bar|fraction.", direction: "row|column.", infinity: "Loop (boolean).", transitionMode: "slide|fade.", transitionTime: "ms.", auto_hide_navigation: "Hide arrows until hover (boolean).", arrowIcon: "Arrow SVG." }, config: { navColor: "Arrow colour.", navSize: "Arrow size (px).", navBackground: "Arrow background.", bulletSizeRow: "Bullet size.", barWidth: "Progress bar width.", fractionFontSize: "Fraction text size." }, events: "tab — fires on slide change.", notes: "Full-width hero/banner slider — holds slide children. The most common homepage hero." },
  slide: { events: "none", notes: "A single slide inside a carousel/swiper." },
  embed: { specials: { iframe: "Raw HTML / iframe markup.", htmlCode: "Raw HTML/JS snippet (type='code').", type: "code | iframe." }, events: "none", notes: "Raw HTML/JS embed — set htmlCode (type:'code') or iframe." },
  googlemap: { specials: { iframe: "Google Maps embed iframe string.", type: "code | place." }, config: { maxHeight: "Map max height (px)." }, events: "none" },
  countdown: { specials: { time: "Target date/time.", type: "Countdown mode.", duration: "Countdown length (s).", repeat: "Restart when finished (boolean).", typeShow: "Largest unit shown (day|minute|…).", showDay: "Show days (boolean).", showHours: "Show hours (boolean).", showSecond: "Show seconds (boolean).", isPromotion: "Tie to a promotion (boolean).", durationStart: "Start datetime.", durationEnd: "End datetime.", dailyStart: "Daily reset start (HH:MM:SS).", dailyEnd: "Daily reset end.", positionTitle: "Title position (top|bottom).", showText: "Show the title text (boolean)." }, config: { bgTop: "Top-digit background.", bgBottom: "Bottom-digit background.", sizeDot: "Separator dot size.", spacingTitle: "Gap to title." }, events: "none", notes: "Countdown timer (flash sale / launch). Set duration or durationStart/End." },
  breadcrumb: { specials: { options: "Per-context paths (search/product/category/blog/post/default).", icon: "Separator string e.g. '>'." }, config: { hoverColor: "Link hover colour." }, events: "none", notes: "Auto-builds the trail (Home › Category › Product) from the current page — common on category/product pages." },
  "list-ordered": { specials: { tableItems: "Column definitions [{name,key,i18nKey}]." }, events: "none" },

  // ── layout ──
  section: {
    specials: { global: "Mark as a global/shared section (reused across pages).", custom_class: "CSS class.", layout: "Nested layout payload (advanced)." },
    config: { stickyPosition: "Make the section sticky: default | autobottom | none.", stickyTop: "Sticky offset from top (px).", showShadowWhenSticky: "Add a shadow when stuck (0/1).", video_background: "Section video background {background_display,…}.", pattern_overlay: "Overlay pattern image url.", apply_pattern_overlay: "Apply the overlay pattern (boolean).", nameLineClamp: "Clamp the section title to N lines." },
    events: "none",
    notes: "Top-level band; centred 3-column grid. Children go in the centre column (new_section handles this). Make a header section sticky with config.stickyPosition; add a video/pattern background via config.",
  },
  container: { specials: { tabIndex: "Tab order.", custom_class: "CSS class.", custom_css: "Raw CSS." }, config: { maxWidth: "Max width.", maxWidthUnit: "Max-width unit.", fixedPosition: "Float/pin the box (e.g. bottom_right) — for back-to-top / chat bubbles.", fixedRight: "Pinned offset from right (px).", fixedBottom: "Pinned offset from bottom (px).", fixedLeft: "Pinned offset from left (px).", stickyPosition: "Sticky mode.", stickyTop: "Sticky offset from top (px).", stickyBottom: "Sticky offset from bottom (px).", pinnedPoint: "Section id where pinning starts.", unpinnedPoint: "Section id where pinning ends.", useAutoScroll: "Auto-scroll the box (boolean).", initMaxHeight: "Collapsed max-height (px).", isUseInitMaxHeight: "Animate from initMaxHeight (boolean).", maxHeight: "Expanded max-height (px).", animation: "Entrance animation." }, events: "click, hover — clickable groups are common.", notes: "Generic grid box; nest children with their own grid. Pin a floating button/sidebar via config.fixedPosition; sticky filters via stickyTop + pinnedPoint/unpinnedPoint." },
  row: { events: "none", notes: "Simple horizontal wrapper." },
  tabs: { specials: { activeTab: "Default active tab index.", tabs: "Tab definitions [{id,name}].", navMode: "How tabs switch: toggle | …", showNav: "Show the tab nav (boolean).", showBullet: "Show bullets (boolean).", showDivider: "Show a divider (boolean)." }, config: { navPosition: "top|left|right|bottom.", alignNav: "Nav alignment.", nav_display_style: "Nav style." }, events: "tab — fires when the active tab changes.", notes: "Tabbed container; each tab maps to a tab item the content reacts to (e.g. account panels, product detail/description/reviews)." },
  collapse: { events: "none", notes: "Accordion container (collapse-item children)." },
  "collapse-item": { events: "none", notes: "One accordion panel." },
  "custom-layout": { events: "none", notes: "Free-form layout container." },
  "layout-dataset": { events: "none", bindings: ["product::*"], notes: "Repeating layout bound to a dataset." },

  // ── button ──
  button: { specials: { text: "Button label." }, events: "click — set the action in events[] (open page/link/scroll/popup/add-to-cart...).", notes: "Label in specials.text; behaviour in events[]." },
  "submit-button": { specials: { text: "Button label (e.g. 'Đăng nhập')." }, events: "submit — submits its parent form.", notes: "Place inside a form." },
  "paypal-button": { events: "none", notes: "PayPal payment button (provider-handled)." },
  "button-login-google": { specials: { text: "Label e.g. 'Đăng nhập với Google'." }, events: "click (OAuth)." },
  "button-login-facebook": { specials: { text: "Label e.g. 'Đăng nhập với Facebook'." }, events: "click (OAuth)." },
  "current-location": { specials: { text: "Label.", field_name: "current location.", field_type: "current-location." }, events: "click (geolocation)." },

  // ── form ──
  form: {
    specials: {
      type: "Form behaviour — one of: form_login | form_signup | form_order | form_discount | subscribe | order_tracking | form_booking | form_search_agency | question_form | customer_data | reset_password | forgot_password.",
      submit_success: "Action after a successful submit (e.g. show a message / redirect).",
      message: "Success message text.",
      show_message: "Show a success message after submit (boolean).",
      show_message_time: "How long the success message stays (seconds).",
      multiForms: "Ids of inner sub-forms this form owns (order forms split fields across an inner form).",
      formParent: "On an inner sub-form: the id of the owning outer form.",
      tabIndex: "Bind the form to a tab item (TAB-ITEM-…) in a tabbed account panel.",
      autoGetInfoCustomer: "Pre-fill from the logged-in customer (boolean).",
      partner_id: "Partner/agency id (booking/search-agency forms).",
      time_otp: "OTP resend countdown (seconds).",
    },
    config: { ...FIELD_CONFIG, borderColor: "Input border colour (e.g. #dbe0e6).", borderRadius: "Input corner radius (e.g. 8px).", labelPadding: "Label padding.", strokeColor: "Text stroke colour.", textColor: "Form text colour." },
    events: "success — fire follow-up actions after a successful submit (a form_order commonly does open_page→Thank-you page). eventName defaults to 'success' on a form.",
    notes: "Wrap input fields as children; put a submit-button inside. specials.type selects what the form does on submit. Real order forms split fields across an inner form via specials.multiForms:[innerFormId] (inner form sets specials.formParent). A form_order uses dedicated field types: input(full_name), phone-number, email, detect-address, address (×3 province/district/ward), text-area(note).",
  },
  input: { specials: { ...FIELD, type: "Input type (default text).", is_manually_added: "Field was added by hand vs auto (boolean)." }, config: { ...FIELD_CONFIG }, events: "none" },
  email: { specials: { ...FIELD, validate_email: "Email regex." }, config: { ...FIELD_CONFIG }, events: "none", notes: "field_name usually 'email'." },
  "phone-number": { specials: { ...FIELD }, config: { ...FIELD_CONFIG }, events: "none", notes: "field_name usually 'phone_number'." },
  "retype-phone-number": { specials: { ...FIELD }, config: { ...FIELD_CONFIG }, events: "none" },
  password: { specials: { ...FIELD, field_type: "password.", validate_p: "Password regex (e.g. ^[a-zA-Z0-9]{6,}$).", validate_password: "Password regex (alt key).", showHidePassword: "Show the eye toggle (boolean)." }, config: { ...FIELD_CONFIG }, events: "none", notes: "field_name 'password'." },
  "retype-password": { specials: { ...FIELD, field_type: "retype-password.", showHidePassword: "Show the eye toggle (boolean)." }, config: { ...FIELD_CONFIG }, events: "none" },
  "current-password": { specials: { ...FIELD, field_type: "current-password.", showHidePassword: "Show the eye toggle (boolean)." }, config: { ...FIELD_CONFIG }, events: "none" },
  "text-area": { specials: { ...FIELD }, config: { ...FIELD_CONFIG }, events: "none", notes: "Multi-line; field_name often 'note'." },
  select: { specials: { ...FIELD, options: "Choices [{id,name}] (or {type,name,image,active}).", defaultValue: "Selected option id.", isRetrieve: "Pre-fill from saved data (boolean).", isHideImage: "Hide option images (boolean)." }, config: { ...FIELD_CONFIG, arrowColor: "Dropdown arrow colour.", strokeColor: "Text stroke.", textColor: "Option text colour." }, events: "none" },
  "group-select": { specials: { ...FIELD, options: "Choices [{id,name}]." }, config: { ...FIELD_CONFIG }, events: "none" },
  checkbox: { specials: { field_name: FIELD.field_name, label: FIELD.label, show_label: FIELD.show_label, required: FIELD.required, options: "Choices [{id,name,connects?}].", defaultValue: "Default checked id ('none').", icon_color: "Check colour.", isRetrieve: "Pre-fill from saved data (boolean)." }, config: { ...FIELD_CONFIG, strokeColor: "Text stroke." }, events: "none" },
  "checkbox-group": { specials: { ...FIELD, ...FILTER_SPECIALS, icon_color: "Check colour.", is_attribute_by_category: "Build options from the category's attributes (boolean)." }, config: { ...FIELD_CONFIG, borderRadiusInput: "Checkbox corner radius.", radioButtonSize: "Checkbox size (px).", spaceButtonText: "Gap between box and label.", strokeColor: "Text stroke.", textColor: "Label colour." }, events: "none", notes: "Doubles as a category-page FILTER: set filter_elements + sync_tab ('brand'/'attribute') to drive a grid-product." },
  "checkbox-item": { specials: { label: "Option text." }, events: "none" },
  radio: { specials: { field_name: FIELD.field_name, label: FIELD.label, show_label: FIELD.show_label, required: FIELD.required, options: "Choices [{id,name}].", defaultValue: "Default selected id.", icon_color: "Dot colour." }, config: { ...FIELD_CONFIG, sizeInput: "Radio size (px).", strokeColor: "Text stroke.", textColor: "Label colour." }, events: "none" },
  "radio-group": { specials: { ...FIELD, ...FILTER_SPECIALS }, config: { ...FIELD_CONFIG, radioButtonSize: "Radio size (px).", spaceButtonText: "Gap between dot and label.", strokeColor: "Text stroke." }, events: "none", notes: "Can act as a FILTER (filter_elements + sync_tab)." },
  address: { specials: { field_name: "province_id/district_id/commune_id.", label: FIELD.label, show_label: FIELD.show_label, useNewAddress: "Use the newer province/district/commune picker (boolean).", isColumn: "Stack the three selects in a column (boolean).", provinceName: "Province placeholder.", districtName: "District placeholder.", communeName: "Commune placeholder.", default_province: "Default province id ('none').", country: "Country code (e.g. 84).", required_province: "Require province.", required_districts: "Require district.", required_commune: "Require commune." }, config: { ...FIELD_CONFIG }, events: "none", notes: "Renders 3 linked selects (province→district→commune). A form_order usually has 3 address elements." },
  "detect-address": { specials: { ...FIELD, field_type: "detect_address." }, config: { ...FIELD_CONFIG }, events: "none", notes: "Free-text address that auto-detects province/district." },
  "postal-code": { specials: { ...FIELD, postal_code: "Regex (e.g. [0-9]{6}).", numberCharacter: "Expected length (e.g. '4_character')." }, config: { ...FIELD_CONFIG }, events: "none" },
  country: { specials: { ...FIELD, countries: "Country list [{country_code,country_name}].", defaultValue: "Default country code (e.g. 'VN')." }, config: { ...FIELD_CONFIG }, events: "none" },
  "input-file": { specials: { ...FIELD, isTransferImage: "Transfer as image (boolean)." }, config: { ...FIELD_CONFIG }, events: "none", notes: "Upload box — usually a dashed optionBorderStyle." },
  "input-number": { specials: { ...FIELD }, config: { ...FIELD_CONFIG }, events: "none" },
  "input-date": { specials: { ...FIELD, type: "date | time.", field_connect_pos: "Map to a POS customer field (e.g. customer_birthday)." }, config: { ...FIELD_CONFIG }, events: "none" },
  "input-search": { specials: { field_name: "search.", label: FIELD.label, placeholder: FIELD.placeholder, showIcon: "Show the search icon (boolean).", searchIcon: "Search icon SVG.", showModalSearch: "Open results in a modal (boolean).", default_search_page: "Where Enter searches ('category_page').", isSearchInCategoryPage: "Search within the current category (boolean).", isSearchInBlogPage: "Search blog too (boolean).", view_keep_keywords: "Keep recent keywords ('category')." }, config: { inputBackground: "Input bg.", inputBorderColor: "Border colour.", inputBorderRadius: "Corner radius.", inputBorderWidth: "Border width.", placeholderColor: "Placeholder colour.", iconColor: "Icon colour.", iconAlign: "left|right.", iconSize: "Icon size (px).", textAlign: "Text alignment." }, events: "onenter — fires a search on Enter.", notes: "Storefront search box; pair with search-droppable for live results." },
  "otp-input": { specials: { ...FIELD, isOpenModalOtp: "Open OTP modal (boolean).", time_otp: "Resend countdown (seconds)." }, config: { ...FIELD_CONFIG }, events: "none" },
  "rating-input": { specials: { field_name: FIELD.field_name, label: FIELD.label, show_label: FIELD.show_label, auto_hide_without_star: "Hide when no rating (boolean).", activeStarIcon: "Filled-star SVG.", inactiveStarIcon: "Empty-star SVG." }, config: { activeStarColor: "Filled star colour.", inactiveStarColor: "Empty star colour." }, events: "none", notes: "Star rating input (review form)." },
  identity: { specials: { ...FIELD }, config: { ...FIELD_CONFIG }, events: "none", notes: "Email-or-phone login field; field_name 'identity'." },
  "search-form": { specials: { ...FIELD, field_type: "search." }, config: { ...FIELD_CONFIG }, events: "none", notes: "A search field inside a form." },
  "search-droppable": { config: { use_overlay: "Dim the page behind the results (boolean).", droppable_position: "Where results open (custom|...)." }, events: "none", notes: "Live search-results dropdown paired with an input-search." },
  "two-point-range": { specials: { filter: "What it filters (e.g. 'filter_price').", min: "Range minimum.", max: "Range maximum.", display_type: "Handle style (round|...).", use_button_filter: "Apply only on a button (boolean)." }, config: { dotColor: "Handle colour.", dotSize: "Handle size (px).", progressColor: "Active track colour.", progressBgColor: "Inactive track colour.", progressSize: "Track thickness (px).", textColor: "Min/max label colour." }, events: "none", notes: "A price (or numeric) RANGE filter for the category page — set filter + filter_elements to drive a grid-product." },
  "color-group": { specials: { ...FILTER_SPECIALS, options: "Swatches [{color, filter:{attrName,...}}].", sync_tab: "attribute (colour variations)." }, config: { colorWidth: "Swatch width.", colorHeight: "Swatch height.", colorGap: "Gap between swatches.", colorBorderRadius: "Swatch radius.", colorBorderColor: "Swatch border.", colorBorderColorActive: "Selected swatch border.", textPosition: "Label position.", hiddenText: "Hide the label (boolean)." }, events: "none", notes: "Colour-swatch FILTER (category page) — filter_elements + sync_tab:'attribute' drive a grid-product." },
  switch: { specials: { defaultValue: "Default on/off (boolean)." }, config: { backgroundSlider: "Track colour.", colorRound: "Knob colour.", colorSlider: "Active track colour." }, events: "none", notes: "Toggle; style width/height." },

  // ── commerce ──
  "grid-product": {
    specials: { displayStyle: "default | only_image | border.", original_price_position: "left | right | top | bottom.", products_per_load: "Products fetched per page/scroll (real range 8–36).", category_id: "Source products from a specific category id (else current category).", show_original_price: "Show the compare-at price (boolean).", show_discount_on_price: "Show a discount badge on the price (boolean).", show_quick_view: "Show a quick-view button on hover (boolean).", show_product_name: "Show the product name (boolean).", show_product_price: "Show the price (boolean).", show_rating: "Show the star rating (boolean).", load_rating: "Fetch ratings for the cards (boolean).", rating_number_type: "Rating count style (review_count|…).", show_ribbon: "Show a ribbon/badge (boolean).", load_brand: "Fetch + show the brand (boolean).", load_category: "Fetch + show the category (boolean).", show_categories: "Show category labels (boolean).", max_show_categories: "Max category labels per card.", show_total_sold: "Show units sold (boolean).", show_wholesale_price: "Show wholesale price (boolean).", show_divider: "Show a divider in the card (boolean).", show_button: "Show an add-to-cart/quick button (boolean).", show_button_on_hover: "Reveal the button only on hover (boolean).", textQuickBtn: "Quick add-to-cart button label.", action_add_to_cart: "Add-to-cart behaviour (numeric mode).", action_attachment_add_to_cart: "After add-to-cart: open_cart | …", scroll_type: "Pagination scroll behaviour (scroll_to_top|…).", type_view_more: "Load-more style.", barValue: "Stock bar source (remain_quantity|…).", saleInfoDisplayText: "In-stock label.", saleInfoSoldoutText: "Sold-out label.", disable_filter: "Ignore active filters (boolean).", disable_search: "Ignore the search query (boolean).", show_detail_price: "Show a detailed price breakdown (boolean).", show_quantity: "Show a quantity stepper on the card (boolean).", show_wholesale_quantity: "Show wholesale tiers (boolean).", auto_hide_without_star: "Hide rating when none (boolean).", promotion_id: "Restrict to a promotion's products.", action_product_card: "Click behaviour for the whole card (numeric mode).", store_show_attribute_template_1: "Attribute-template plugin config {show_cart,…}.", filledStarIcon: "Filled-star SVG.", unfilledStarIcon: "Empty-star SVG.", on_hover: "Card hover effect: zoom | swap (swap to 2nd image).", randomDisplay: "Randomise product order (boolean).", typeLinkCategory: "Related-products source: similar_product | products_viewed.", plugins: "Extra card plugins [{name,type,icon}] (e.g. attribute templates, extra info)." },
    config: { columns: "Products per row (real range 1–6).", responsive: "autofit | fixed | custom (fixed keeps the column count; custom collapses on mobile).", item_show: "How many products to show.", image_ratio: "INDUSTRY-DEPENDENT: 4/5 fashion · 2/3 kids · 3/4 food · 1/1 square (cosmetics/electronics). Also 16/9|3/2|4/3|9/16.", img_object_fit: "cover|contain|fill|stretch.", image_border_radius: "Card image corner radius (px).", image_placement: "Image vs text layout (column|row).", gap_column: "Column gap (real range 8–40).", gap_row: "Row gap (real range 0–40).", product_info_padding_y: "Vertical padding of the name/price block (px).", price_padding_y: "Vertical padding around the price (px).", price_padding_x: "Horizontal padding around the price (px).", product_info_alignment: "left|center|right.", productNameFont: "Product-name font family.", productNameFontSize: "Product-name font size (px, real 12–18).", productNameFontWeight: "Product-name weight.", productNameColor: "Product-name colour.", productNameHover: "Product-name hover colour.", productNamePaddingY: "Vertical padding of the name (px).", productCategoryFontSize: "Category-label size (px).", productPriceFont: "Price font family.", productPriceFontSize: "Price font size (px).", productPriceFontWeight: "Price font weight — bold across ALL surveyed templates.", productPriceColor: "Price colour (often a theme accent / var).", productOriginalPriceFontSize: "Compare-at price font size (px).", productOriginalPriceColor: "Compare-at price colour (muted grey).", cardBackground: "Card background colour.", ribbonBackground: "Ribbon background.", ribbonFont: "Ribbon font.", ribbonPadding: "Ribbon padding.", ribbonGap: "Ribbon gap.", customRibbonStyle: "Per-ribbon style overrides {ribbonId:{…}}.", paginationColor: "Pagination dot colour.", activePaginationColor: "Active pagination colour.", sizeThumbnail: "{ width, height } of the card image." },
    events: "none",
    bindings: ["product::product_image", "product::product_name", "product::product_price"],
    notes: "Lists store products (self-renders image+name+price card). Requires a 'store' page / use_store. Config is INDUSTRY-DEPENDENT (surveyed fashion/kids/cosmetics/food/electronics): only bold price + responsive collapse + show original/discount are near-universal; pick image_ratio/columns/gaps/fonts/colours to match the brand.",
  },
  "slider-product": { specials: { displayStyle: "default|only_image|border.", original_price_position: "left|right|top.", category_id: "Source category id.", products_per_load: "Products to fetch.", autoplay: "on|off.", autoplay_time: "ms per slide.", autoplay_step: "Slides advanced per step.", on_hover: "zoom|swap.", show_navigation: "Show arrows (boolean).", show_nav_on_hover: "Reveal arrows on hover (boolean).", arrow_icon: "Arrow SVG.", show_rating: "Show rating (boolean).", show_ribbon: "Show ribbon (boolean).", show_product_name: "Show name (boolean).", show_product_price: "Show price (boolean).", show_button: "Show add-to-cart button (boolean).", action_add_to_cart: "Add-to-cart mode.", typeLinkCategory: "Related source (similar_product|…).", randomDisplay: "Randomise order (boolean)." }, config: { slideItems: "Visible products.", item_show: "Visible products (real 1–6, fractional ok e.g. 3.6).", slideWidth: "Card width.", image_ratio: "Aspect ratio (industry-dependent, see grid-product).", productNameFontSize: "Name size.", productPriceFontWeight: "Price weight (bold).", productPriceColor: "Price colour.", image_border_radius: "Card image radius.", sizeThumbnail: "{width,height} of card image." }, events: "none", bindings: ["product::product_image", "product::product_name", "product::product_price"], notes: "Horizontal product carousel (homepage 'featured/related'). Same card config family as grid-product + slider keys (item_show, autoplay, arrows)." },
  "product-gallery": { specials: { showNavigation: "Show the thumbnail strip / nav (boolean — real templates often false).", show_ribbon: "Show a ribbon on the image (boolean).", zoom_type: "Hover zoom: none | lens | …", on_hover: "Hover effect on the main image (e.g. zoom).", arrowColor: "Nav arrow colour.", autoplay: "Auto-advance images (on|off).", autoplay_video: "Auto-play a product video (boolean).", type_split_video: "How a video splits from images (none|…).", infinity: "Loop images (boolean).", auto_resize_height: "Fit height to image (boolean)." }, config: { sizeThumbnail: "{ width, height } of the main image (real 500–1044).", image_ratio: "Main image ratio (often 'auto').", img_object_fit: "cover|contain.", showThumbnail: "Show the thumbnail strip (boolean).", thumbnailPosition: "left|bottom|…", thumbnailWidth: "Thumb width (px).", thumbnailHeight: "Thumb height (px).", scrollDirection: "Thumb scroll axis (horizontal|vertical).", arrowWidth: "Arrow width.", arrowHeight: "Arrow height.", max_show_items: "Max thumbnails shown." }, events: "none", notes: "Product detail image gallery (product page): main image + thumbnail strip (thumbnailPosition) + optional hover zoom (zoom_type)." },
  "product-image-carousel": { events: "none", notes: "Product image carousel (product page)." },
  "cart-items": { events: "none", bindings: ["cart_item::cart_item_image", "cart_item::cart_item_name", "cart_item::cart_item_price", "cart_item::cart_item_total_price", "cart_item::cart_item_prod_attr"], notes: "Cart line items (cart page). A repeater whose config.columns defines the per-row column template — real templates use [70px image, 1fr name, ~240px price, ~116px qty, ~240px total, 34px remove]." },
  "cart-icon": { specials: { svg: "Icon SVG (defaults to a bag icon; fill='currentColor' so it inherits style.color).", itemCount: "Badge count (0 placeholder)." }, config: { itemCountFontFamily: "Badge font family.", itemCountFont: "Badge font (theme var).", itemCountFontSize: "Badge font size (e.g. 11px).", itemCountFontWeight: "Badge font weight.", itemCountColor: "Badge text colour.", itemBackgroundColor: "Badge background colour.", itemCountBorderRadius: "Badge corner radius (50% = circle)." }, events: "click — opens cart. Real templates wrap it in a container with open_popup(mouseenter)/close_popup(mouseleave) for a mini-cart, plus a container with open_page→cart page." },
  "quantity-input": { specials: { spinner: "Native spinner style: hide-spin (product/cart, the default) | circle (checkout).", showLeftBtn: "Show the minus button (boolean).", showRightBtn: "Show the plus button (boolean).", min: "Minimum quantity.", max: "Maximum quantity." }, config: { textColor: "Quantity text colour.", btnIncrease: "Plus-button style {borderColor,background,…}.", btnDecrease: "Minus-button style." }, events: "none", notes: "Quantity stepper (product/cart). Defaults to spinner:'hide-spin'." },
  attr: { specials: { attrName: "Attribute to show, or 'auto'.", autoAttrName: "Resolved attribute name when attrName='auto' (e.g. Màu sắc, Kích thước).", autoNamePriority: "Order when auto (1,2,3…).", attrPrimary: "This is the primary variation (boolean).", layout: "Swatch layout variant (1,4…).", defaultSelected: "Pre-select the first option (boolean).", tooltip: "Show a tooltip on hover (boolean)." }, config: { borderColorHover: "Swatch hover border colour.", type: "Display: hover | regular.", selectedType: "Selected style (outer|…).", sizeImage: "Image swatch size (px).", tooltipBackground: "Tooltip background.", tooltipColor: "Tooltip text colour.", tooltipPosition: "top|bottom|…" }, events: "none", notes: "Product attribute/variation selector (product page). Add one attr per variation axis (colour, size); attrName:'auto' lets it resolve from the product." },
  payment: { specials: { options: "Payment methods [{type,name,image,active}].", icon_color: "Method icon colour.", runNow: "Auto-run the selected method (boolean)." }, config: { activeColor: "Selected-method colour." }, events: "none", notes: "Payment methods block (checkout)." },
  "delivery-method": { specials: { options: "[{type: delivery|store_pickup, name, active}]." }, events: "none" },
  "order-items": { events: "none", bindings: ["order_item::product_image", "order_item::product_name", "order_item::product_quantity", "order_item::product_attrs", "order_item::items_sum_up_price"], notes: "Order summary lines (checkout/thank-you). Repeater whose config.columns is the per-row template — real templates use [75px image, 1fr name, 95px price]." },
  "order-history": { specials: { items_per_load: "Orders per page.", type_view_more: "Load-more style.", editView: "Layout mode (data|…).", default_filter: "Default status filter ids.", countdown_time: "Auto-cancel countdown (hours).", cancel_text: "Cancel-order label.", order_id_text: "Order-code label.", payment_text: "Payment label.", total_price_text: "Total label.", item_attr_text: "Variation label.", is_scroll_to_top: "Scroll up on page change (boolean)." }, config: { show_variation: "Show item variations (boolean).", productNameClamp: "Clamp product name lines.", imageSize: "Thumbnail size (px).", priceColor: "Price colour." }, events: "none", notes: "Member order history (member page)." },
  coupon: { specials: { field_name: "coupon.", label: FIELD.label, placeholder: FIELD.placeholder, show_label: FIELD.show_label, required: FIELD.required, title: "Heading text.", auto_fill_coupon: "Pre-fill an available coupon (boolean)." }, config: { ...FIELD_CONFIG }, events: "none", notes: "Coupon / discount-code input (cart/checkout). Place inside a form_discount." },
  "product-overlay": { specials: { type: "discount | custom." }, events: "none", notes: "Badge overlaid on a product card." },
  "product-review": {
    specials: {
      title: "Heading text.", show_heading: "Show the heading (boolean).", reviews_per_page: "Reviews per page.",
      show_avatar: "Show reviewer avatar (boolean).", avatar_size: "Avatar size (px).", reply_avatar_size: "Reply avatar size (px).",
      avatar_border_radius: "Avatar corner radius.", avatar_border_color: "Avatar border colour.", avatar_border_size: "Avatar border width.",
      show_rating_breakdown: "Show the star breakdown (boolean).", show_sorting: "Show sort control (boolean).", show_filter: "Show filter (boolean).",
      show_publish_date: "Show the review date (boolean).", require_email: "Require email to review (boolean).", require_phone_number: "Require phone (boolean).",
      type_view_more: "How more reviews load (paginate/expand).",
    },
    events: "none", notes: "Product reviews block (product page).",
  },
  "number-step": {
    specials: {
      minValue: "Minimum value.", maxValue: "Maximum value.", numberUnit: "Unit label.", count: "Step amount.",
      filter: "Filter mode.", use_button_filter: "Use buttons to filter (boolean).", shortened: "Abbreviate large numbers (boolean).",
    },
    events: "none", notes: "Numeric stepper / counter.",
  },
  "masonry-review": { specials: { view_product_mode: "How linked products display in the review wall." }, events: "none", notes: "Masonry wall of reviews." },
  "flash-sale": { specials: { promotion_advance_id: "Promotion id (or 'none')." }, events: "none" },
  promotions: { specials: { displayPromotions: "Which promotion kinds to list (e.g. ['coupon_id_multiple_times','discount_by_coupon'])." }, config: { direction: "horizontal | vertical.", promotionBorderColor: "Card border colour.", promotionDotColor: "Perforation dot colour." }, events: "none", bindings: ["promotion_item::image", "promotion_item::name", "promotion_item::code", "promotion_item::description", "promotion_item::end_date"], notes: "Lists active promotions/coupons (often with a copy-code button)." },
  "promotions-short": { specials: { displayPromotions: "Promotion kinds to list." }, config: { direction: "horizontal | vertical.", promotionBorderColor: "Border colour.", promotionDotColor: "Dot colour." }, events: "none", bindings: ["promotion_item::name", "promotion_item::code"] },
  "grid-category": { specials: { showCategories: "Categories to show [{id,...}] (else all).", isAutoCatchMenuLevelFirst: "Auto-pick top-level categories (boolean)." }, config: { columns: "Categories per row.", minimum_card_width: "Min card width (autofit, px).", sizeThumbnail: "{width,height} of the category image.", responsive: "fixed | autofit.", imageBorderRadius: "Image radius (px).", cardBackground: "Card background.", cardBorderRadius: "Card radius.", name_padding_y: "Padding around the name." }, events: "none", notes: "Lists product categories. Create categories first (create_product_category)." },
  "slider-category": { specials: { showCategories: "Categories to show [{id,...}].", on_hover: "Card hover effect (zoom-in|…)." }, config: { columns: "Visible categories.", minimum_card_width: "Min card width (px).", sizeThumbnail: "{width,height} of the image.", imageBorderRadius: "Image radius.", navSize: "Arrow size (px).", arrowColor: "Arrow colour." }, events: "none" },
  "customer-address": { events: "none", bindings: ["customer_address::full_name", "customer_address::address", "customer_address::phone_number", "customer_address::pdc", "customer_address::is_default"], notes: "Member saved addresses." },
  wishlist: { specials: { svg: "Icon SVG.", itemCount: "Badge count." }, config: { itemCountColor: "Badge text colour.", itemBackgroundColor: "Badge background.", itemCountFontSize: "Badge size.", itemCountFontWeight: "Badge weight.", itemCountBorderRadius: "Badge radius.", itemCountFontFamily: "Badge font." }, events: "click — opens the wishlist." },
  "favorite-icon": { events: "click — toggle favourite." },
  "bonus-items": { specials: { typeBonus: "combo_product | other." }, events: "none" },

  // ── navigation ──
  menu: { specials: { type: "horizontal | vertical | hamburger | collapse | grid | anchor.", sync: "Auto-sync items with site pages (boolean).", fullField: "Stretch items to fill the menu width (boolean).", shapeType: "'Icon' to render a hamburger/icon trigger instead of text.", url: "Icon image url (icon-style menu).", isPostList: "Build items from blog posts (boolean).", tabIndex: "Bind to a tab item." }, config: { showArrow: "Show the dropdown caret on items with a submenu (boolean).", textColor: "Item text colour (often a theme var like var(--color_20)).", colorHover: "Item hover colour.", activeColor: "Active item colour.", "--padX": "Horizontal padding inside each item (CSS var, e.g. 15px).", mask: "Icon SVG mask (icon-style menu).", arrowColor: "Caret colour.", arrowSize: "Caret size (px).", backgroundHover: "Item hover background.", borderColorHover: "Item hover border colour.", borderRadiusHover: "Item hover radius.", fontWeightHover: "Item hover font weight.", activeLink: "Active-item style object (e.g. {fontWeight:'bold'}).", maxHeight: "Max dropdown height (px)." }, events: "none", notes: "Holds menu-item children. Real headers carry TWO menus (a horizontal desktop menu + a hamburger/collapse mobile menu). Colour items via theme vars (var(--color_20))." },
  "menu-item": { specials: { name: "Link label.", isCustom: "Custom link (boolean).", isSync: "Auto-synced from site pages (boolean).", linkType: "page | category | blog_category | brand | product_tag | custom.", linkPage: "Target page id (linkType=page).", pageId: "Target page id (mirror of linkPage, set both).", linkCategory: "Linked product category id.", linkCategoryTarget: "Open target for the category (_self/_blank).", linkBlogCategory: "Linked blog category id.", link: "Custom href (linkType=custom).", categoryId: "Category id.", syncSubmenu: "Auto-build submenu (boolean).", type: "vertical for a stacked submenu item." }, config: { strokeColor: "Text stroke colour." }, events: "navigation lives in SPECIALS here, NOT events — set linkType + the matching id.", notes: "For a page link set linkType='page' + linkPage + pageId + name. Category → linkType='category' + linkCategory. Custom url → linkType='custom' + link + isCustom. (Generic text/container/button navigate via events:[{action:'open_page',open_page_id}].)" },
  "menu-anchor-item": { specials: { name: "Label.", isCustom: "Custom.", linkType: "Link kind.", anchor: "Target anchor id on the page.", categoryId: "Category id." }, events: "click — scrolls to an anchor." },
  submenu: { specials: { syncSubmenu: "Auto-build from child pages/categories (boolean).", type: "vertical | horizontal.", effect: "Open animation (fade-in|…).", timeAnim: "Animation duration (s)." }, events: "none", notes: "Dropdown panel under a menu-item." },
  "menu-droppable": { specials: { effect: "Open animation (light-speed|fade-in|…).", timeAnim: "Animation duration (s)." }, config: { isUseInitMaxHeight: "Animate from a max-height (boolean)." }, events: "none", notes: "Mega-menu panel under a menu-item (holds a nested menu + content)." },
  "member-bar": { specials: { showView: "Which state to show: not_logged | logged.", layoutShow: "avatar | text | …", textLogin: "Login label.", textSignup: "Signup label.", textLogout: "Logout label.", textBeforeLogin: "Text shown before login.", login_icon: "Login icon SVG.", signup_icon: "Signup icon SVG.", login_popup: "Popup id opened for login.", register_popup: "Popup id opened for signup.", show_signup: "Show the signup option (boolean).", event_type: "What clicking does (open_page|open_popup).", open_when_logged: "Logged-in behaviour (collapse|…).", arrowShape: "Dropdown arrow shape." }, config: { avatarSize: "Avatar size (px).", colorIcon: "Icon colour.", memberColorHover: "Hover colour.", bgDropdown: "Dropdown background.", justifyBar: "Bar alignment." }, events: "click — login/logout/open account.", notes: "Account bar: shows login/signup when logged out, avatar+menu when logged in. member-dropdown is its dropdown panel." },
  "member-dropdown": { specials: { dropdown_position: "left | right." }, events: "none", notes: "The account dropdown under a member-bar." },
  dropdown: { specials: { placeholder: "Closed-state label (e.g. 'Thứ tự mặc định').", options: "Choices [{id,name}].", count: "How many options.", is_default_select: "Pre-select the first (boolean).", filter_elements: "Grid-product id(s) this sort/filter controls.", sync_tab: "What it syncs from (category|…).", redirect_type: "Navigate on select (none|page).", redirect_id: "Target id when redirecting.", arrowIcon: "Arrow SVG.", use_button_filter: "Apply only on a button (boolean)." }, config: { arrowColor: "Arrow colour.", arrowSize: "Arrow size (px).", strokeColor: "Text stroke.", textColor: "Text colour." }, events: "click/hover — toggles dropdown-content. Commonly a product SORT control on the category page (set filter_elements).", notes: "Product sort/filter dropdown, or a generic toggle for dropdown-content." },
  "dropdown-content": { events: "none", notes: "The panel a dropdown toggles." },
  "language-menu": { specials: { show_flag: "Show country flags (boolean).", type: "dropdown | inline." }, config: { display: "full | abbreviated.", flagSize: "Flag size (px).", color: "Text colour.", colorHover: "Hover colour.", backgroundDropdown: "Dropdown background.", colorSelected: "Selected language colour.", dropdown_icon_size: "Caret size (px)." }, events: "none", notes: "Language switcher (multilingual sites)." },

  // ── blog ──
  "post-list": { specials: { numbers_posts_to_show: "Total posts to show.", numbers_posts_to_show_per_page: "Posts per page.", posts_display_by: "Source mode (category/recent/…).", category_id: "Blog category id (or 'similar_posts').", readButtonText: "Read-more label.", on_hover: "Card hover effect (zoom).", tagTitle: "Title HTML tag (h3…).", tagDescription: "Description tag.", tagDatePublished: "Date tag.", tagCategory: "Category tag." }, config: { posts_per_row: "Posts per row.", image_ratio: "Card image ratio (3/2|1/1|…).", image_align: "Image position (top|left).", imageBorderRadius: "Image radius (px).", responsive: "fixed | custom.", spacing_between_posts: "Gap between cards (px).", showCategory: "Show category (0/1).", showPublishDate: "Show date (0/1).", showDescription: "Show excerpt (0/1).", showReadButton: "Show read-more (0/1).", descriptionFontSize: "Excerpt size.", descriptionColor: "Excerpt colour.", dateColor: "Date colour." }, events: "none", notes: "Lists blog articles (children are post-overlay cards). Create blog category + articles first." },
  "slider-post": { specials: { numbers_posts_to_show: "Posts to show.", category_id: "Blog category id (or 'all_posts').", readButtonText: "Read-more label.", on_hover: "Hover effect (zoom)." }, config: { slideItems: "Visible posts.", slideWidth: "Card width.", posts_per_row: "Posts per view.", image_ratio: "Card image ratio.", responsive: "fixed | custom.", spacing_between_posts: "Gap (px).", layout: "Card layout variant." }, events: "none" },
  "grid-blog": { specials: { showBlogs: "Categories to show [{...}]." }, config: { columns: "Posts per row." }, events: "none" },
  "slider-blog": { specials: { showBlogs: "Categories to show." }, config: { columns: "Visible posts." }, events: "none" },
  "post-overlay": { specials: { type: "regular | custom." }, events: "none", notes: "Post card overlay (post page)." },
  "blog-overlay": { specials: { type: "regular | custom." }, events: "none" },

  // ── filters / widgets / states (mined from 34 templates) ──
  tags: { specials: { ...FILTER_SPECIALS, activeMode: "How active tags render.", selectionMode: "single | multiple.", auto_category_type: "Auto-source: product_category | …", auto_option: "Behaviour on click: filter | redirect.", max_child_categories: "Max child categories listed.", use_filter_or: "OR vs AND across selected tags (boolean).", keyword_suggestions: "Suggested search keywords [{key,value}]." }, config: { tags_layout: "Tag layout style." }, events: "click — filters the linked grid-product (or redirects).", notes: "Tag/attribute/keyword chips that FILTER a product grid (category page) — set filter_elements + sync_tab:'tag'; or auto_option:'redirect' to navigate." },
  "auto-number": { specials: { startNumber: "Start value.", endNumber: "End value.", jumpNumber: "Increment step.", duration: "Count-up duration (s)." }, config: { strokeColor: "Text stroke.", textColor: "Number colour." }, events: "none", notes: "Animated count-up stat (e.g. '10,000+ customers')." },
  agency: { specials: { datagrid_id: "Linked data grid id.", googleTarget: "Google-map target." }, config: { hoverColor: "Hover colour.", activeColor: "Active colour." }, events: "none", bindings: ["agency::name", "agency::phone_number", "agency::address", "agency::time"], notes: "Store-locator / branch list (repeater over agency::*)." },
  "user-point-log": { specials: { itemGap: "Row gap.", noteColor: "Note colour.", datetimeColor: "Date colour." }, events: "none", notes: "Loyalty reward-point history (member page)." },
  "empty-product-layout": { events: "none", notes: "Empty-state shown inside a grid-product when no products match." },
  "cart-items-empty": { events: "none", notes: "Empty-state shown inside cart-items when the cart is empty." },
  "cart-droppable": { events: "none", notes: "Mini-cart drawer/panel (header). Open via open_cart / open_popup." },
  "lesson-sidebar": { specials: { submit_status: "Lesson completion state." }, config: { backgroundModule: "Module background.", iconSize: "Icon size (px)." }, events: "none", notes: "Course lesson navigation sidebar (course app)." },
  "lesson-items": { events: "none", notes: "Lessons list inside a module (course app)." },
  "next-lesson-droppable": { events: "none", notes: "Next-lesson panel (course app)." },
  "list-lesson-droppable": { events: "none", notes: "Lessons droppable list (course app)." },
};

const describe = (type: string, key: string, where: "specials" | "config"): string | undefined => {
  const curated = ELEMENT_ATTRS[type] || {};
  return (curated[where] && curated[where]![key]) || SHARED_KEY_DICT[key] || (where === "specials" ? SHARED_SPECIALS[key] : undefined);
};

/**
 * Build a COMPLETE attribute report for an element type, merging three sources:
 *  - curated tables (ELEMENT_ATTRS) + dictionaries (human meaning),
 *  - the full real key surface mined from published pages + factory defaults (OBSERVED),
 *  - the live skeleton (factory defaults).
 * Every real key is surfaced; ones we have meaning for are described, the rest are
 * listed by name so the AI knows they exist. No invented keys.
 */
export function describeAttributes(type: string, skeleton: any): any {
  const curated = ELEMENT_ATTRS[type] || {};
  const obs = OBSERVED[type] || { specials: [], config: [], style: [], bindings: [], events: false };
  const skSpecials = (skeleton && skeleton.specials) || {};
  const skConfig = (skeleton && ((skeleton.runtime && skeleton.runtime.config) || skeleton.config)) || {};

  // ── specials: every real key, described where known ──
  const specialKeys = new Set<string>([
    ...Object.keys(curated.specials || {}),
    ...obs.specials,
    ...Object.keys(skSpecials),
  ]);
  const specials: Record<string, string> = {};
  const moreSpecials: string[] = [];
  for (const k of [...specialKeys].sort()) {
    if (NOISE_KEYS.has(k) || k in SHARED_SPECIALS) continue; // shared ones listed separately
    const d = describe(type, k, "specials");
    if (d) specials[k] = d;
    else moreSpecials.push(k);
  }

  // ── config: element-specific only (drop generic grid/position internals) ──
  const configKeys = new Set<string>([
    ...Object.keys(curated.config || {}),
    ...obs.config,
    ...Object.keys(skConfig),
  ]);
  const config: Record<string, string> = {};
  const moreConfig: string[] = [];
  for (const k of [...configKeys].sort()) {
    if (NOISE_KEYS.has(k) || GENERIC_CONFIG.has(k)) continue;
    const d = describe(type, k, "config");
    if (d) config[k] = d;
    else moreConfig.push(k);
  }

  const style = (obs.style || []).filter((k) => !NOISE_KEYS.has(k)).sort();

  return {
    specials: Object.keys(specials).length ? specials : undefined,
    more_specials: moreSpecials.length ? moreSpecials : undefined, // real but un-annotated
    common_specials: Object.keys(SHARED_SPECIALS), // available on almost every element
    config: Object.keys(config).length ? config : undefined,
    more_config: moreConfig.length ? moreConfig : undefined, // real but un-annotated (mostly visual)
    style: style.length ? style : undefined,
    events: curated.events || (obs.events ? "supports events[] (click/hover/submit actions)" : "none observed"),
    bindings: (curated.bindings && curated.bindings.length ? curated.bindings : obs.bindings) || undefined,
    notes: curated.notes,
    common_specials_note: "custom_class/custom_css/element_async/event_name_custom work on almost every element.",
    layout_hint: "runtime.style holds CSS (width/height/color/fontSize/background/border…); runtime.config holds grid placement (see get_build_guide). On save these expand into bp1..bp4.",
    events_hint: "Attach interactions via opts.events (ids auto-minted). Call list_events for the trigger/action catalog + required fields.",
    bindings_hint: "Attach dynamic data via opts.bindings (ids auto-minted). Call list_bindings for the dataset/field catalog. Inside a repeater (grid-product/cart-items/post-list…) children bind to the per-item dataset.",
    coverage: obs.seen ? `${obs.seen} real instances mined` : "factory default only",
  };
}
